-- veille-patrimoine — chargement du référentiel dans Supabase (v2026-09-17)
-- À exécuter APRÈS schema.sql, dans SQL Editor. Ré-exécutable (upsert).

insert into acteurs (acteur_id,nom,type,organisation,camp,statut,date_statut,priorite,frequence_veille,site_officiel,url_programme,notes,actif,maj_par,maj_le) values
  ('le-pen-marine','Marine Le Pen','candidat','Rassemblement national','droite_nationale','declare','2026-07-07','P1','quotidien',null,null,'Déclarée au 20h de TF1 ; pourvoi en cassation en cours (éligibilité)',true,'Elora Lazaar','2026-09-14'),
  ('philippe-edouard','Édouard Philippe','candidat','Horizons','centre','declare','2024-09-03','P1','quotidien',null,null,'Déclaré dès septembre 2024',true,'Elora Lazaar','2026-09-14'),
  ('attal-gabriel','Gabriel Attal','candidat','Renaissance','centre','declare','2026-05-22','P1','quotidien',null,null,null,true,'Elora Lazaar','2026-09-14'),
  ('retailleau-bruno','Bruno Retailleau','candidat','Les Républicains','droite','investi','2026-04-19','P1','quotidien',null,null,'Investi par les adhérents LR (73,8 %)',true,'Elora Lazaar','2026-09-14'),
  ('melenchon-jean-luc','Jean-Luc Mélenchon','candidat','La France insoumise','gauche','declare','2026-05-31','P1','quotidien',null,null,'4e candidature ; date de confirmation fin mai 2026 à préciser',true,'Elora Lazaar','2026-09-14'),
  ('glucksmann-raphael','Raphaël Glucksmann','candidat','Place publique','gauche','primaire',null,'P1','quotidien',null,null,'Candidat à la primaire PS / Place publique / GRS',true,'Elora Lazaar','2026-09-14'),
  ('bertrand-xavier','Xavier Bertrand','candidat','Nous France','droite','a_confirmer',null,'P2','hebdo',null,null,'Statut validé par E. Lazaar le 2026-09-14 ; source presse à joindre',true,'Elora Lazaar','2026-09-14'),
  ('lisnard-david','David Lisnard','candidat','Nouvelle Énergie','droite','declare',null,'P2','hebdo',null,null,'A quitté LR en avril 2026',true,'Elora Lazaar','2026-09-14'),
  ('roussel-fabien','Fabien Roussel','candidat','Parti communiste français','gauche','investi','2026-09-06','P2','hebdo',null,null,'Candidature validée par les adhérents PCF (72 %)',true,'Elora Lazaar','2026-09-14'),
  ('tondelier-marine','Marine Tondelier','candidat','Les Écologistes','ecologiste','declare',null,'P2','hebdo',null,null,null,true,'Elora Lazaar','2026-09-14'),
  ('faure-olivier','Olivier Faure','candidat','Parti socialiste','gauche','primaire',null,'P2','hebdo',null,null,'Candidat à la primaire PS',true,'Elora Lazaar','2026-09-14'),
  ('guedj-jerome','Jérôme Guedj','candidat','Parti socialiste','gauche','primaire','2026-02-05','P2','hebdo',null,null,'Déclaré le 5 fév. 2026, a rejoint la primaire PS en août',true,'Elora Lazaar','2026-09-14'),
  ('bouamrane-karim','Karim Bouamrane','candidat','Parti socialiste','gauche','declare','2026-06-09','P2','hebdo',null,null,'Maire de Saint-Ouen ; positionnement vis-à-vis de la primaire à suivre',true,'Elora Lazaar','2026-09-14'),
  ('royal-segolene','Ségolène Royal','candidat','Sans étiquette (ex-PS)','gauche','primaire','2026-07-10','P2','hebdo',null,null,'Candidate à la primaire PS',true,'Elora Lazaar','2026-09-14'),
  ('brun-philippe','Philippe Brun','candidat','Parti socialiste','gauche','primaire',null,'P2','hebdo',null,null,'Député ; candidat à la primaire PS, ligne salaires',true,'Elora Lazaar','2026-09-14'),
  ('ruffin-francois','François Ruffin','candidat','Debout !','gauche','declare',null,'P2','hebdo',null,null,'Maintien annoncé, primaire ou non',true,'Elora Lazaar','2026-09-14'),
  ('dupont-aignan-nicolas','Nicolas Dupont-Aignan','candidat','Debout la France','souverainiste','declare',null,'P3','mensuel',null,null,null,true,'Elora Lazaar','2026-09-14'),
  ('philippot-florian','Florian Philippot','candidat','Les Patriotes','souverainiste','declare',null,'P3','mensuel',null,null,null,true,'Elora Lazaar','2026-09-14'),
  ('asselineau-francois','François Asselineau','candidat','Union populaire républicaine','souverainiste','declare',null,'P3','mensuel',null,null,null,true,'Elora Lazaar','2026-09-14'),
  ('batho-delphine','Delphine Batho','candidat','Génération écologie','ecologiste','declare',null,'P3','mensuel',null,null,null,true,'Elora Lazaar','2026-09-14'),
  ('arthaud-nathalie','Nathalie Arthaud','candidat','Lutte ouvrière','extreme_gauche','declare',null,'P3','mensuel',null,null,'4e candidature',true,'Elora Lazaar','2026-09-14'),
  ('kazib-anasse','Anasse Kazib','candidat','Révolution permanente','extreme_gauche','declare',null,'P3','mensuel',null,null,null,true,'Elora Lazaar','2026-09-14'),
  ('labib-selma','Selma Labib','candidat','NPA-Révolutionnaires','extreme_gauche','declare',null,'P3','mensuel',null,null,null,true,'Elora Lazaar','2026-09-14'),
  ('branco-juan','Juan Branco','candidat','Les Ruches','gauche','declare','2025-12-19','P3','mensuel',null,null,null,true,'Elora Lazaar','2026-09-14'),
  ('egger-clara','Clara Egger','candidat','Solution démocratique','autre','declare',null,'P3','mensuel',null,null,'Démocratie directe / RIC',true,'Elora Lazaar','2026-09-14'),
  ('massard-lydie','Lydie Massard','candidat','Union démocratique bretonne','autre','a_confirmer',null,'P3','mensuel',null,null,'Décision de maintien attendue en septembre 2026',true,'Elora Lazaar','2026-09-14'),
  ('institut-montaigne','Institut Montaigne','think_tank',null,'na','na',null,'P1','hebdo','https://www.institutmontaigne.org/',null,null,true,'Elora Lazaar','2026-09-14'),
  ('fondapol','Fondapol','think_tank',null,'na','na',null,'P1','hebdo','https://www.fondapol.org/',null,null,true,'Elora Lazaar','2026-09-14'),
  ('terra-nova','Terra Nova','think_tank',null,'na','na',null,'P1','hebdo','https://tnova.fr/',null,null,true,'Elora Lazaar','2026-09-14'),
  ('ofce','OFCE','think_tank',null,'na','na',null,'P1','hebdo','https://www.ofce.fr/',null,'Chiffrages de programmes en 2017 et 2022 ; blog séparé',true,'Elora Lazaar','2026-09-14'),
  ('institut-choiseul','Institut Choiseul','think_tank',null,'na','na',null,'P2','hebdo','https://www.choiseul.info/',null,null,true,'Elora Lazaar','2026-09-14'),
  ('croissance-plus','Croissance Plus','club',null,'na','na',null,'P2','hebdo','https://croissanceplus.com/',null,null,true,'Elora Lazaar','2026-09-14'),
  ('medef','MEDEF','organisation',null,'na','na',null,'P1','hebdo',null,null,'Site à renseigner',true,'Elora Lazaar','2026-09-14'),
  ('cgt','CGT','organisation',null,'na','na',null,'P2','hebdo',null,null,'Site à renseigner',true,'Elora Lazaar','2026-09-14'),
  ('cfdt','CFDT','organisation',null,'na','na',null,'P2','hebdo',null,null,'Site à renseigner',true,'Elora Lazaar','2026-09-14'),
  ('fo','Force ouvrière','organisation',null,'na','na',null,'P2','hebdo',null,null,'Site à renseigner',true,'Elora Lazaar','2026-09-14'),
  ('assemblee-nationale','Assemblée nationale – commission des finances','institution',null,'na','na',null,'P1','hebdo',null,null,'Comptes rendus, propositions de loi, données ouvertes',true,'Elora Lazaar','2026-09-14'),
  ('senat','Sénat – commission des finances','institution',null,'na','na',null,'P2','hebdo',null,null,'Rapports et comptes rendus',true,'Elora Lazaar','2026-09-14'),
  ('gouvernement','Gouvernement / PLF 2027','institution',null,'na','na',null,'P1','quotidien','https://www.budget.gouv.fr/',null,'Mesures budgétaires en cours (PLF/PLFSS 2027) : dons familiaux, donations temporaires, désindexation…',true,'Elora Lazaar','2026-09-17'),
  ('fondation-ifrap','Fondation iFRAP','think_tank',null,'na','na',null,'P1','hebdo','https://www.ifrap.org/','https://www.ifrap.org/comparateurs/presidentielles-2027','Think tank libéral ; comparateur de programmes et chiffrages',true,'Elora Lazaar','2026-09-17'),
  ('zemmour-eric','Éric Zemmour','candidat','Reconquête','droite_nationale','a_confirmer',null,'P3','mensuel',null,null,'Non déclaré à la date du 17/09/2026 ; propositions détaillées dans le JDD et iFRAP',true,'Elora Lazaar','2026-09-17')
on conflict (acteur_id) do update set
  nom=excluded.nom, type=excluded.type, organisation=excluded.organisation, camp=excluded.camp, statut=excluded.statut,
  date_statut=excluded.date_statut, priorite=excluded.priorite, frequence_veille=excluded.frequence_veille,
  site_officiel=excluded.site_officiel, url_programme=excluded.url_programme, notes=excluded.notes, actif=excluded.actif,
  maj_par=excluded.maj_par, maj_le=excluded.maj_le;

insert into sources (source_id,acteur_id,type_source,url,mode_collecte,frequence,langue,fiabilite,robots_ok,actif,notes) values
  ('montaigne-rss','institut-montaigne','rss','https://www.institutmontaigne.org/rss.xml','auto','quotidien','fr','primaire','na',false,'URL RSS déduite, à confirmer avant activation'),
  ('montaigne-publications','institut-montaigne','page_web','https://www.institutmontaigne.org/publications','auto','hebdo','fr','primaire','na',true,'Surveillance de la page publications ; URL à confirmer'),
  ('fondapol-rss','fondapol','rss','https://www.fondapol.org/feed/','auto','quotidien','fr','primaire','na',false,'URL RSS déduite (WordPress), à confirmer'),
  ('tnova-rss','terra-nova','rss','https://tnova.fr/feed/','auto','quotidien','fr','primaire','na',false,'URL RSS déduite (WordPress), à confirmer'),
  ('ofce-site-rss','ofce','rss','https://www.ofce.fr/feed/','auto','hebdo','fr','primaire','na',false,'URL RSS déduite, à confirmer'),
  ('ofce-blog','ofce','rss','https://www.ofce.sciences-po.fr/blog/feed/','auto','hebdo','fr','primaire','na',false,'Blog OFCE ; URL à confirmer'),
  ('choiseul-rss','institut-choiseul','rss','https://www.choiseul.info/feed/','auto','hebdo','fr','primaire','na',false,'URL RSS déduite, à confirmer'),
  ('croissanceplus-rss','croissance-plus','rss','https://croissanceplus.com/feed/','auto','hebdo','fr','primaire','na',false,'URL RSS déduite, à confirmer'),
  ('croissanceplus-actualites','croissance-plus','page_web','https://croissanceplus.com/','auto','hebdo','fr','primaire','na',true,'Surveillance page d''accueil / actualités'),
  ('medef-presse','medef','page_web',null,'auto','hebdo','fr','primaire','na',false,'Page communiqués de presse à renseigner'),
  ('cgt-presse','cgt','page_web',null,'auto','hebdo','fr','primaire','na',false,'Page communiqués de presse à renseigner'),
  ('cfdt-presse','cfdt','page_web',null,'auto','hebdo','fr','primaire','na',false,'Page communiqués de presse à renseigner'),
  ('fo-presse','fo','page_web',null,'auto','hebdo','fr','primaire','na',false,'Page communiqués de presse à renseigner'),
  ('an-cfin','assemblee-nationale','parlement',null,'auto','hebdo','fr','primaire','na',false,'Flux commission des finances / open data à renseigner'),
  ('senat-cfin','senat','parlement',null,'auto','hebdo','fr','primaire','na',false,'Flux commission des finances à renseigner'),
  ('le-pen-marine-site','le-pen-marine','page_web',null,'auto','quotidien','fr','primaire','na',false,'Site de campagne à renseigner ; surveillance changement de page'),
  ('le-pen-marine-programme','le-pen-marine','pdf',null,'manuel','mensuel','fr','primaire','na',false,'URL du programme à renseigner dès publication'),
  ('le-pen-marine-youtube','le-pen-marine','youtube',null,'manuel','hebdo','fr','primaire','na',false,'Chaîne ou playlists d''interviews à renseigner ; transcription'),
  ('philippe-edouard-site','philippe-edouard','page_web',null,'auto','quotidien','fr','primaire','na',false,'Site de campagne à renseigner ; surveillance changement de page'),
  ('philippe-edouard-programme','philippe-edouard','pdf',null,'manuel','mensuel','fr','primaire','na',false,'URL du programme à renseigner dès publication'),
  ('philippe-edouard-youtube','philippe-edouard','youtube',null,'manuel','hebdo','fr','primaire','na',false,'Chaîne ou playlists d''interviews à renseigner ; transcription'),
  ('attal-gabriel-site','attal-gabriel','page_web',null,'auto','quotidien','fr','primaire','na',false,'Site de campagne à renseigner ; surveillance changement de page'),
  ('attal-gabriel-programme','attal-gabriel','pdf',null,'manuel','mensuel','fr','primaire','na',false,'URL du programme à renseigner dès publication'),
  ('attal-gabriel-youtube','attal-gabriel','youtube',null,'manuel','hebdo','fr','primaire','na',false,'Chaîne ou playlists d''interviews à renseigner ; transcription'),
  ('retailleau-bruno-site','retailleau-bruno','page_web',null,'auto','quotidien','fr','primaire','na',false,'Site de campagne à renseigner ; surveillance changement de page'),
  ('retailleau-bruno-programme','retailleau-bruno','pdf',null,'manuel','mensuel','fr','primaire','na',false,'URL du programme à renseigner dès publication'),
  ('retailleau-bruno-youtube','retailleau-bruno','youtube',null,'manuel','hebdo','fr','primaire','na',false,'Chaîne ou playlists d''interviews à renseigner ; transcription'),
  ('melenchon-jean-luc-site','melenchon-jean-luc','page_web',null,'auto','quotidien','fr','primaire','na',false,'Site de campagne à renseigner ; surveillance changement de page'),
  ('melenchon-jean-luc-programme','melenchon-jean-luc','pdf',null,'manuel','mensuel','fr','primaire','na',false,'URL du programme à renseigner dès publication'),
  ('melenchon-jean-luc-youtube','melenchon-jean-luc','youtube',null,'manuel','hebdo','fr','primaire','na',false,'Chaîne ou playlists d''interviews à renseigner ; transcription'),
  ('glucksmann-raphael-site','glucksmann-raphael','page_web',null,'auto','quotidien','fr','primaire','na',false,'Site de campagne à renseigner ; surveillance changement de page'),
  ('glucksmann-raphael-programme','glucksmann-raphael','pdf',null,'manuel','mensuel','fr','primaire','na',false,'URL du programme à renseigner dès publication'),
  ('glucksmann-raphael-youtube','glucksmann-raphael','youtube',null,'manuel','hebdo','fr','primaire','na',false,'Chaîne ou playlists d''interviews à renseigner ; transcription'),
  ('bertrand-xavier-site','bertrand-xavier','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('lisnard-david-site','lisnard-david','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('roussel-fabien-site','roussel-fabien','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('tondelier-marine-site','tondelier-marine','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('faure-olivier-site','faure-olivier','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('guedj-jerome-site','guedj-jerome','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('bouamrane-karim-site','bouamrane-karim','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('royal-segolene-site','royal-segolene','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('brun-philippe-site','brun-philippe','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('ruffin-francois-site','ruffin-francois','page_web',null,'auto','hebdo','fr','primaire','na',false,'Site de campagne à renseigner'),
  ('dupont-aignan-nicolas-programme','dupont-aignan-nicolas','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('philippot-florian-programme','philippot-florian','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('asselineau-francois-programme','asselineau-francois','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('batho-delphine-programme','batho-delphine','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('arthaud-nathalie-programme','arthaud-nathalie','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('kazib-anasse-programme','kazib-anasse','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('labib-selma-programme','labib-selma','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('branco-juan-programme','branco-juan','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('egger-clara-programme','egger-clara','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('massard-lydie-programme','massard-lydie','pdf',null,'manuel','mensuel','fr','primaire','na',false,'Programme publié uniquement ; veille mensuelle'),
  ('ifrap-comparateur','fondation-ifrap','page_web','https://www.ifrap.org/comparateurs/presidentielles-2027','auto','hebdo','fr','secondaire','na',false,'Surveillance des changements du comparateur ; à activer après vérification robots.txt'),
  ('gouvernement-budget','gouvernement','page_web','https://www.budget.gouv.fr/','auto','hebdo','fr','primaire','na',false,'Communiqués et dossiers de presse du budget ; URL précise à renseigner')
on conflict (source_id) do update set
  acteur_id=excluded.acteur_id, type_source=excluded.type_source, url=excluded.url, mode_collecte=excluded.mode_collecte,
  frequence=excluded.frequence, langue=excluded.langue, fiabilite=excluded.fiabilite, robots_ok=excluded.robots_ok,
  actif=excluded.actif, notes=excluded.notes;
